compilation:
  cloud_properties: {}
  network: nfs-net
  workers: 1
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18
jobs:
- instances: 1
  log_level: debug
  name: nfsbroker
  networks:
  - name: nfs-net
  properties:
    nfsbroker:
      plan-id: existing
      plan-name: existing
      service-id: nfs-volume
      service-name: nfs-volume
      password: admin
    route_registrar:
      routes:
      - name: nfsbroker
        port: 8999
        registration_interval: 20s
        tags:
          component: nfsbroker
        uris:
        - nfsbroker.bosh-lite.com
  resource_pool: nfs-resourcepool
  templates:
  - name: nfsbroker
    release: nfs-volume
  - name: route_registrar
    release: cf
name: nfs-volume
networks:
- name: nfs-net
  subnets:
  - cloud_properties: {}
    gateway: 10.244.8.1
    range: 10.244.8.0/24
    static:
    - 10.244.8.8
  type: manual
properties:
  nfsbroker:
    plan-desc: free nfs filesystem for bosh-lite
  nats:
    machines:
    - 10.244.0.6
    password: nats
    port: 4222
    user: nats
releases:
- name: nfs-volume
  version: latest
- name: cf
  version: latest
resource_pools:
- cloud_properties: {}
  name: nfs-resourcepool
  network: nfs-net
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000
